### ISSUE TITLE
Team Meeting - Thursday Feb 15, 2018

### ISSUE THREAD

**Issue by pfitzpaddy** [immap-dev/angular-dashboard-prototype#1]
Thanks for the time today Fakhri. I have added some list of things below;

**Tasks**
- [x] Overflow bug (form component) when adding rows
- [x] Action buttons on cards should always be <mat-card-actions>
- [x] Implement Cascading Select http://xlsform.org/#cascade
- [x] Ability to theme application
- [x] Review code and make modular components

**Investigate**
- [x] Minify, AOT, gzip
- [x] Investigate TDD and how that might be done (services, components)
- [x] Check out 'Formsets' on http://demo.viewflow.io/, (Login -> Form sample -> Formsets  )

![viewflow-formsets](https://user-images.githubusercontent.com/1784705/36245756-aa41fbde-123d-11e8-94b5-033bbafee598.png)

**Comment by pfitzpaddy** [comment]
Good work, well done
