### ISSUE TITLE
Team Meeting - Tuesday Feb 28, 2018

### ISSUE THREAD

**Issue by pfitzpaddy** [immap-dev/angular-dashboard-prototype#3]
**Tasks**
- [x] Harry to update style and layout https://github.com/immap-dev/angular-dashboard-prototype/issues/2
- [ ] Timur to review ReportHub functionality and add issues for further component development in RH2
- [ ] Review CI/CD repo made by Mohammad https://github.com/iMMAP/rh
